#!/usr/bin/python
#
# Copyright (c) 2005-2007 Canonical
#
# AUTHOR:
# Michael Vogt <mvo@ubuntu.com>
#
# This file is part of GDebi
#
# GDebi is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# GDebi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GDebi; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

import sys
import apt
import os.path
import gettext
from gettext import gettext as _


from GDebi.GDebiCli import GDebiCli

# FIXME: - add "--assume-yes" option
#        - add check for removal of essential packages

if __name__ == "__main__":
    localesApp="gdebi"
    localesDir="/usr/share/locale"
    gettext.bindtextdomain(localesApp, localesDir)
    gettext.textdomain(localesApp)

    if not sys.argv[1:] or sys.argv[1] == "-h" or sys.argv[1] == "--help":
        print _("Usage: %s [package.deb]" % sys.argv[0])
        print
        print _("To use the graphical user interface, right-click\n" \
                "on a '.deb' software package in the file browser\n" \
                "and select: Open with 'GDebi Package Installer'.")
        sys.exit(1)
    if not os.path.exists(sys.argv[1]):
        print _("gdebi error, file not found: %s" % sys.argv[1])
        sys.exit(1)

    debi = GDebiCli() 
    if not debi.open(sys.argv[1]):
        sys.exit(1)
    print _("Do you want to install the software package? [y/N]:"),
    sys.stdout.flush()
    res = sys.stdin.readline()
    # TRANSLATORS: the first char in a "Yes" word
    if res.upper().startswith(_("Y")):
        debi.install()
