#!/usr/bin/python2.4

import sys
import apt
import os.path


from GDebi import GDebiCli


if __name__ == "__main__":
    debi = GDebiCli() 
    if not debi.open(sys.argv[1]):
        sys.exit(1)
    print "Do you want to install it [yN]:",
    sys.stdout.flush()
    res = sys.stdin.readline()
    if res.startswith("y") or res.startswith("Y"):
        debi.install()
