.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GDEBI 1 "Dec 23, 2005"
.SH NAME
gdebi \- Simple tool to install deb files
.SH SYNOPSIS
.B gdebi [package.deb]
.SH DESCRIPTION
gdebi lets you install local deb packages resolving and installing
its dependencies. apt does the same, but only for remote (http, ftp)
located packages.
.SH AUTHOR
This manual page was written by Gustavo Franco <stratus@debian.org>,
for the Debian project (but may be used by others).
